<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="Init_PB_Main_75x75" Id="{8ad3235a-704a-4061-89e4-6ea28658faa8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION Init_PB_Main_75x75 : INT

VAR_INPUT
END_VAR

VAR

END_VAR

VAR_IN_OUT
	COMP:TS_Component;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[COMP.B_TYPE:=1;
COMP.size:=1;]]></ST>
    </Implementation>
    <LineIds Name="Init_PB_Main_75x75">
      <LineId Id="677" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>